version: "3.7"

services:

  recipemanager-service:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    container_name: recipemanager
    hostname: recipemanager
    ports:
      - "0.0.0.0:8080:80"
    environment:                                                                
      PGHOST: my_db
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: 5432
      PGDATABASE: ${PGDATABASE}
    volumes:
      - ../:/usr/src/app
    depends_on:
      - my_db
    networks:
      - internal-network
      - cluster

  my_db:
    image: postgres:12
    container_name: my_db
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - ${PGPORT}:5432
    volumes:
      - database-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal-network

  db-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "30001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test
      PGADMIN_DEFAULT_PASSWORD: test
    logging: 
      driver: none
    networks:
      - internal-network

volumes:
  database-volume:

networks:
  internal-network:
  cluster:
    external: true